#!/usr/bin/env bash
#
# Check that CHDB_VERSION in the public header belongs to this ClickHouse line.
# When a tag is provided, also check that the public ABI reports that exact tag.
#
#   .github/scripts/check-abi-version.sh
#   .github/scripts/check-abi-version.sh v26.7.0
#
# chdb_version() returns that macro and nothing else, so it is the only thing the C
# ABI says about itself and there is nothing to cross-check it against. It sat at
# 26.5.1-rc.3 through v26.7.0, two ClickHouse lines behind the engine around it.
#
# The first two fields must move with the ClickHouse line in
# cmake/autogenerated_versions.txt. The exact third field is checked only when
# cutting a tag, because release candidates may either reuse or advance it.
#
# Separate from check-release-tag.sh because the checks fail for unrelated
# reasons: a red check should say which.

set -euo pipefail

TAG="${1:-}"
HEADER=programs/local/chdb.h
VERSIONS=cmake/autogenerated_versions.txt

[ -f "$HEADER" ] || {
	echo "::error::$HEADER is missing, so there is nothing to check the tag against" >&2
	exit 1
}

[ -f "$VERSIONS" ] || {
	echo "::error::$VERSIONS is missing, so there is nothing to check CHDB_VERSION against" >&2
	exit 1
}

declared=$(sed -n 's/^#define CHDB_VERSION "\(.*\)"$/\1/p' "$HEADER" | head -1)
[ -n "$declared" ] || {
	echo "::error::$HEADER has no CHDB_VERSION define" >&2
	exit 1
}

upstream=$(sed -n 's/^SET(VERSION_STRING \([0-9.]*\))$/\1/p' "$VERSIONS" | head -1)
describe=$(sed -n 's/^SET(VERSION_DESCRIBE \(.*\))$/\1/p' "$VERSIONS" | head -1)
[ -n "$upstream" ] || {
	echo "::error::$VERSIONS has no VERSION_STRING line" >&2
	exit 1
}

declared_line=$(echo "$declared" | sed -n 's/^\([0-9][0-9]*\.[0-9][0-9]*\)\..*$/\1/p')
[ -n "$declared_line" ] || {
	cat >&2 <<EOF
::error::$HEADER declares CHDB_VERSION as $declared, which does not start with X.Y.Z.

CHDB_VERSION must start with the ClickHouse line, such as 26.7.0 or
26.7.1-rc.2, so the release scripts can check it against $VERSIONS.
EOF
	exit 1
}

upstream_line=$(echo "$upstream" | cut -d. -f1-2)
if [ "$declared_line" != "$upstream_line" ]; then
	cat >&2 <<EOF
::error::CHDB_VERSION is not on the ClickHouse line this tree is synced to.

  $HEADER says          $declared
  the tree is synced to $upstream_line   ($VERSIONS, $upstream, $describe)

Update CHDB_VERSION in $HEADER when syncing to a new ClickHouse line, so
chdb_version() does not report an older engine line.
EOF
	exit 1
fi

[ -n "$TAG" ] || {
	echo "$HEADER declares $declared on ClickHouse line $upstream_line (tree is at $upstream, $describe)"
	exit 0
}

want=${TAG#v}

if [ "$declared" != "$want" ]; then
	cat >&2 <<EOF
::error::the version compiled into the library is not the version being released.

  $HEADER says   $declared
  the tag says   $want

chdb_version() returns the first of those, so every caller asking the library what
it is would be told $declared. Bump CHDB_VERSION in $HEADER, then move the tag onto
that commit.
EOF
	exit 1
fi

echo "$HEADER declares $declared, matching tag $TAG and ClickHouse line $upstream_line"
