#!/usr/bin/env bash
#
# Check that CHDB_VERSION in the public header belongs to this ClickHouse line.
#
#   .github/scripts/check-abi-version.sh
#
# chdb_version() returns that macro and nothing else, so it is the only thing the C
# ABI says about itself and there is nothing to cross-check it against. It sat at
# 26.5.1-rc.3 through v26.7.0, two ClickHouse lines behind the engine around it.
#
# The exact release is not checked here, because it is not this file's to get right:
# a release build overwrites the macro from the tag before compiling, and passes the
# same value to CMake so chdbVersion() exists at all. What is left to check is that
# the committed value — the one a local build with no tag reports — is at least on
# the line this tree is synced to.
#
# Separate from check-release-tag.sh because the checks fail for unrelated
# reasons: a red check should say which.

set -euo pipefail

HEADER=programs/local/chdb.h
VERSIONS=cmake/autogenerated_versions.txt

[ -f "$HEADER" ] || {
	echo "::error::$HEADER is missing, so there is nothing to check the tag against" >&2
	exit 1
}

[ -f "$VERSIONS" ] || {
	echo "::error::$VERSIONS is missing, so there is nothing to check CHDB_VERSION against" >&2
	exit 1
}

declared=$(sed -n 's/^#define CHDB_VERSION "\(.*\)"$/\1/p' "$HEADER" | head -1)
[ -n "$declared" ] || {
	echo "::error::$HEADER has no CHDB_VERSION define" >&2
	exit 1
}

upstream=$(sed -n 's/^SET(VERSION_STRING \([0-9.]*\))$/\1/p' "$VERSIONS" | head -1)
describe=$(sed -n 's/^SET(VERSION_DESCRIBE \(.*\))$/\1/p' "$VERSIONS" | head -1)
[ -n "$upstream" ] || {
	echo "::error::$VERSIONS has no VERSION_STRING line" >&2
	exit 1
}

# The third field has to be there and be a number, and anything after it has to look
# like our -rc.N, because this is the only thing standing between a mistyped hand edit
# and a version the engine reports. Matching .* there would accept 26.7. and 26.7.foo
# while the error below promises X.Y.Z.
declared_line=$(echo "$declared" | sed -n 's/^\([0-9][0-9]*\.[0-9][0-9]*\)\.[0-9][0-9]*\(-[A-Za-z0-9][A-Za-z0-9.]*\)\{0,1\}$/\1/p')
[ -n "$declared_line" ] || {
	cat >&2 <<EOF
::error::$HEADER declares CHDB_VERSION as $declared, which does not start with X.Y.Z.

CHDB_VERSION must start with the ClickHouse line, such as 26.7.0 or
26.7.1-rc.2, so the release scripts can check it against $VERSIONS.
EOF
	exit 1
}

upstream_line=$(echo "$upstream" | cut -d. -f1-2)
if [ "$declared_line" != "$upstream_line" ]; then
	cat >&2 <<EOF
::error::CHDB_VERSION is not on the ClickHouse line this tree is synced to.

  $HEADER says          $declared
  the tree is synced to $upstream_line   ($VERSIONS, $upstream, $describe)

Update CHDB_VERSION in $HEADER when syncing to a new ClickHouse line, so
chdb_version() does not report an older engine line.
EOF
	exit 1
fi

echo "$HEADER declares $declared on ClickHouse line $upstream_line (tree is at $upstream, $describe)"
