#!/usr/bin/env bash
#
# Check that a release tag names the ClickHouse line this tree is synced to.
#
#   .github/scripts/check-release-tag.sh v26.7.3-rc.2
#
# A chdb release is a ClickHouse baseline plus this repository's own changes, and
# the tag is the only place a user ever sees either of them. So the tag is split:
#
#   vX.Y   the ClickHouse line this tree is synced to, and it has to match
#   .Z     this repository's count of kernel changes on that line, free to move
#
# Syncing 26.7.2.1 means tagging v26.7.something. Which something is up to whoever
# cuts the release: v26.7.1 and v26.7.2 can both sit on ClickHouse 26.7.2, and the
# difference in the third field is how a user learns that the engine's behaviour
# moved even though upstream did not. Upstream's own third and fourth fields count
# its patch releases within a line and have nowhere to go here — a tag carrying
# them would have no room left to say anything about this repository.
#
# Candidates take a new third field each, alongside the rc number:
#
#   v26.7.1-rc.1  ->  v26.7.2-rc.2  ->  v26.7.3
#
# because a candidate that fixes something is a kernel change like any other. This
# script does not enforce that progression; it sees one tag and not the history, so
# it checks the shape and the line and leaves the counting to whoever releases.
#
# Two shapes are accepted and nothing else:
#
#   vX.Y.Z        a release
#   vX.Y.Z-rc.N   the Nth candidate for one
#
# Not out of tidiness. Both bindings derive their own package version from this tag
# by parsing it — chdb-go's internal/enginetag, chdb-node's
# scripts/check-version-scheme.mjs — and each knows these two shapes and refuses
# everything else. A tag outside them cannot be packaged downstream at all.
#
# The upstream version comes from cmake/autogenerated_versions.txt, which
# ci/jobs/scripts/create_release.py maintains, so it says what was actually merged
# rather than what anyone remembers merging.

set -euo pipefail

TAG="${1:-}"
[ -n "$TAG" ] || {
	echo "usage: $0 <tag>" >&2
	exit 2
}

VERSIONS=cmake/autogenerated_versions.txt
[ -f "$VERSIONS" ] || {
	echo "::error::$VERSIONS is missing, so there is nothing to check the tag against" >&2
	exit 1
}

upstream=$(sed -n 's/^SET(VERSION_STRING \([0-9.]*\))$/\1/p' "$VERSIONS" | head -1)
describe=$(sed -n 's/^SET(VERSION_DESCRIBE \(.*\))$/\1/p' "$VERSIONS" | head -1)
[ -n "$upstream" ] || {
	echo "::error::$VERSIONS has no VERSION_STRING line" >&2
	exit 1
}

# No leading zeros in any field. chdb-go reads the fields as numbers, so v26.07.3
# and v26.7.3 reach it as the same release and would be published under one module
# version that the Go proxy then pins to whichever got there first.
num='(0|[1-9][0-9]*)'
if [[ ! $TAG =~ ^v$num\.$num\.$num(-rc\.$num)?$ ]]; then
	cat >&2 <<EOF
::error::tag $TAG is neither vX.Y.Z nor vX.Y.Z-rc.N.

Those are the only two shapes the bindings can parse — chdb-go's
internal/enginetag and chdb-node's scripts/check-version-scheme.mjs — so a tag
outside them is not packageable downstream at all. A fourth field, a missing v, a
-beta or -stable suffix, an rc with no number after it, a field padded to 07: each
stops here. Delete the tag and push the one you meant.
EOF
	exit 1
fi

major=${BASH_REMATCH[1]}
minor=${BASH_REMATCH[2]}
patch=${BASH_REMATCH[3]}

# 26.7.2.1 -> 26.7. Everything after the line is either upstream's patch counting,
# which the tag drops, or this repository's, which the tag is free to choose.
line=$(echo "$upstream" | cut -d. -f1-2)

if [ "$patch" -gt 99 ]; then
	cat >&2 <<EOF
::error::tag $TAG has a third field of $patch, and it has to stay below 100.

chdb-go packs the release into one number — major*10000 + minor*100 + patch — so
that lib/<platform> can stay on a zero major forever and never need a /vN path
suffix. A third field of 100 carries into the minor and lands on a number some
other release already owns, under a module version the Go proxy caches
permanently and will not let go of.

Two digits is the budget for changes on one ClickHouse line. Reaching v$line.99
means it is time to sync upstream, not to widen the field.
EOF
	exit 1
fi

if [ "$minor" -gt 99 ]; then
	cat >&2 <<EOF
::error::tag $TAG has a minor of $minor, which the bindings cannot encode.

The same two-digit packing that limits the third field limits this one, and this
one comes from upstream, so nothing can be tagged on the $line line until
chdb-go's internal/enginetag and chdb-node's scripts/check-version-scheme.mjs
agree on a wider encoding.
EOF
	exit 1
fi

if [ "$major.$minor" != "$line" ]; then
	cat >&2 <<EOF
::error::tag $TAG is not on the ClickHouse line this tree is synced to.

  tag says               $major.$minor
  the tree is synced to  $line   ($VERSIONS, $describe)

The first two fields are how a user reads which ClickHouse they are getting.
Tag v$line.Z instead, picking the third field up where the last release on this
line left off — v$line.Z-rc.N while it is still a candidate — or sync the tree to
the line the tag claims.
EOF
	exit 1
fi

echo "$TAG is on the synced ClickHouse line $line (tree is at $upstream, $describe)"
