#!/usr/bin/env python3
"""Read-only risk inventory for a chdb-core ClickHouse baseline sync."""

from __future__ import annotations

import argparse
import collections
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[4]

RISK_RULES = collections.OrderedDict(
    [
        ("embedded-lifecycle", re.compile(r"^(programs/local/|src/Interpreters/Context|src/Core/ServerSettings)")),
        ("memory-allocator", re.compile(r"^(src/Common/(Allocator|AllocationInterceptors|CurrentMemoryTracker|MemoryTracker|MemoryWorker|malloc|memory|ThreadPool|SignalHandlers)|src/IO/SharedThreadPools|src/Core/BackgroundSchedulePool|contrib/jemalloc-cmake/)")),
        ("c-abi-exports", re.compile(r"^(programs/local/chdb|chdb/libchdb_export|chdb/build(_mac_on_linux)?\.sh)")),
        ("static-archive", re.compile(r"^(programs/local/ForceFunctionReferences|chdb/build/(create_minimal_libchdb|create_static_libchdb|extract_chdb_objects|generate_force_references|check_static_lib_hermetic|test_go_example|go-example/)|contrib/libcxx|contrib/libcxxabi|contrib/libunwind)")),
        ("arrow-parquet-python", re.compile(r"^(contrib/(arrow|pybind11)|src/Processors/Formats/Impl/(Arrow|CHColumnToArrow)|programs/local/(StorageArrow|Python|Pandas|ListScan)|tests/.*(arrow|parquet|python|pandas))")),
        ("lite-wasm-registration", re.compile(r"^(CMakeLists\.txt|src/(Functions|AggregateFunctions)/CMakeLists\.txt|programs/local/ForceFunctionReferences|chdb/build-wasm|\.github/workflows/wasm|tests/test_chdb_core_lite)")),
        ("toolchain-packaging", re.compile(r"^(cmake/|pyproject\.toml|chdb/vars\.sh|\.github/workflows/|contrib/corrosion-cmake/)")),
    ]
)

NO_OP_PREFIXES = (
    "docs/en/",
    "programs/client/",
    "programs/compressor/",
    "programs/extract-from-config/",
    "programs/git-import/",
    "programs/keeper-converter/",
    "programs/keeper-data-dumper/",
    "programs/keeper-utils/",
    "programs/obfuscator/",
    "programs/static-files-disk-uploader/",
    "programs/zookeeper-remove-by-list/",
)

NO_OP_EXACT = {"programs/keeper/dashboard.html"}

UPSTREAM_ADD_EXCLUDED_PREFIXES = (
    ".claude/",
    ".cursor/",
    ".github/",
    "ci/",
    "docker/",
    "docs/",
    "tests/",
    "utils/",
)


def git(*args: str, check: bool = True) -> str:
    proc = subprocess.run(
        ["git", *args],
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if check and proc.returncode:
        raise RuntimeError(proc.stderr.strip() or f"git {' '.join(args)} failed")
    return proc.stdout


def resolve(ref: str) -> str:
    return git("rev-parse", "--verify", f"{ref}^{{commit}}").strip()


def parse_name_status(old_ref: str, new_ref: str) -> list[tuple[str, list[str]]]:
    raw = git("diff", "--name-status", "-M", "-C", old_ref, new_ref)
    records: list[tuple[str, list[str]]] = []
    for line in raw.splitlines():
        cols = line.split("\t")
        if len(cols) >= 2:
            records.append((cols[0], cols[1:]))
    return records


def submodule_paths(ref: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for line in git("ls-tree", f"{ref}:contrib").splitlines():
        meta, path = line.split("\t", 1)
        mode, obj_type, oid = meta.split()
        if mode == "160000" and obj_type == "commit":
            result[f"contrib/{path}"] = oid
    return result


def read_version(ref: str) -> str:
    body = git("show", f"{ref}:cmake/autogenerated_versions.txt", check=False)
    match = re.search(r"SET\(VERSION_DESCRIBE\s+([^\)]+)\)", body, re.I)
    return match.group(1) if match else "<not found>"


def scoped_candidate(status: str, paths: list[str], base_paths: set[str]) -> tuple[bool, str]:
    code = status[0]
    old_path = paths[0]
    new_path = paths[-1]
    if code in {"M", "T"}:
        retained = new_path in base_paths
        return retained, "modified and retained" if retained else "modified but absent from chDB base"
    if code == "D":
        retained = old_path in base_paths
        return retained, "deleted upstream and retained by chDB" if retained else "deleted but absent from chDB base"
    if code == "A":
        excluded = (
            new_path in NO_OP_EXACT
            or new_path.startswith(NO_OP_PREFIXES)
            or new_path.startswith(UPSTREAM_ADD_EXCLUDED_PREFIXES)
        )
        return not excluded, "new relevant path" if not excluded else "new path in known no-op/excluded tree"
    if code in {"R", "C"}:
        keep = old_path in base_paths or new_path in base_paths
        return keep, "rename/copy intersects chDB base" if keep else "rename/copy does not intersect chDB base"
    return False, f"unclassified status {status}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--from-ref", required=True, help="Old ClickHouse tag/ref; prefer refs/tags/<tag>")
    parser.add_argument("--to-ref", required=True, help="New ClickHouse tag/ref; prefer refs/tags/<tag>")
    parser.add_argument("--base-ref", default="origin/main", help="chdb-core branch to sync onto")
    parser.add_argument("--max-files", type=int, default=40, help="Maximum paths printed per risk group")
    args = parser.parse_args()

    try:
        old_oid = resolve(args.from_ref)
        new_oid = resolve(args.to_ref)
        base_oid = resolve(args.base_ref)
        records = parse_name_status(args.from_ref, args.to_ref)
        base_paths = set(git("ls-tree", "-r", "--name-only", args.base_ref).splitlines())
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2

    print("chdb-core ClickHouse baseline sync preflight")
    print(f"repository : {ROOT}")
    print(f"base       : {args.base_ref} ({base_oid[:12]})")
    print(f"base ver   : {read_version(args.base_ref)}")
    print(f"from       : {args.from_ref} ({old_oid[:12]})")
    print(f"to         : {args.to_ref} ({new_oid[:12]})")
    print(f"upstream changed records: {len(records)}")

    status = git("status", "--short")
    print(f"working tree: {'DIRTY (preserve user changes; use a separate worktree)' if status else 'clean'}")

    scoped: list[tuple[str, str, str]] = []
    skipped: collections.Counter[str] = collections.Counter()
    all_paths: set[str] = set()
    added_paths: list[str] = []
    for change, paths in records:
        all_paths.update(paths)
        if change.startswith("A"):
            added_paths.append(paths[-1])
        keep, reason = scoped_candidate(change, paths, base_paths)
        rendered = " -> ".join(paths)
        if keep:
            scoped.append((change, rendered, reason))
        else:
            skipped[reason] += 1

    print(f"scoped candidate records: {len(scoped)}")
    print("scoped candidates:")
    for change, rendered, reason in scoped:
        print(f"  {change}\t{rendered} ({reason})")
    if skipped:
        print("excluded/skipped summary:")
        for reason, count in skipped.most_common():
            print(f"  {count:6d}  {reason}")

    old_sub = submodule_paths(args.from_ref)
    new_sub = submodule_paths(args.to_ref)
    changed_subs = sorted(set(old_sub) | set(new_sub))
    changed_subs = [p for p in changed_subs if old_sub.get(p) != new_sub.get(p)]
    print(f"changed submodule gitlinks: {len(changed_subs)}")
    for path in changed_subs:
        print(f"  {path}: {old_sub.get(path, '<added>')[:12]} -> {new_sub.get(path, '<deleted>')[:12]}")

    risk_groups: dict[str, list[str]] = {name: [] for name in RISK_RULES}
    for path in sorted(all_paths):
        for name, pattern in RISK_RULES.items():
            if pattern.search(path):
                risk_groups[name].append(path)

    print("high-risk upstream changes:")
    for name, paths in risk_groups.items():
        print(f"  {name}: {len(paths)}")
        for path in paths[: args.max_files]:
            print(f"    {path}")
        if len(paths) > args.max_files:
            print(f"    ... {len(paths) - args.max_files} more")

    suspicious_adds = [
        p
        for p in added_paths
        if p in NO_OP_EXACT
        or p.startswith(NO_OP_PREFIXES)
        or p.startswith(("tests/queries/", "tests/integration/", ".claude/", ".cursor/"))
    ]
    print(f"policy-sensitive upstream additions: {len(suspicious_adds)}")
    for path in suspicious_adds[: args.max_files]:
        print(f"  {path}")

    print("next checks:")
    print("  This report is an inventory. It does not decide which paths or conflicts are safe.")
    print("  1. Review references/guide.md before generating the scoped patch.")
    print("  2. Verify every changed gitlink against matching contrib/<lib>-cmake sources.")
    print("  3. Review every high-risk group even when Git reports no conflict.")
    print("  4. Snapshot main CI before attributing failures to the sync.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
