/**
 * chdbStreamInsertTest.c
 *
 * Native C test for the streaming INSERT API (chdb_stream_insert family) —
 * the write-side dual of chdb_stream_query. Coverage mirrors the Python-level
 * suite (tests/test_streaming_insert*.py) minus Python-specific semantics,
 * plus C-only NULL-argument hardening.
 *
 * Verifies:
 *   1.  Full lifecycle: insert -> append -> done reports rows/bytes written,
 *       and the data reads back with exact values.
 *   2.  Input-format matrix: TSV, JSONEachRow (regression for the
 *       parallel-parsing init hang), Values.
 *   3.  True multi-chunk streaming: 20k one-row appends — exact count/sum.
 *   4.  True multi-block streaming: small insert-block SETTINGS make the
 *       worker push multiple blocks (>= 2 MergeTree parts) incrementally.
 *   5.  Appends are binary-safe: only `len` bytes are consumed.
 *   6.  Empty stream: done() after zero appends commits zero rows.
 *   7.  Post-done contract: append fails with CHDBError, a second done()
 *       reports "already finalized", destroy stays safe.
 *   8.  A malformed row surfaces an error no later than done() and nothing
 *       is committed.
 *   9.  Single-active-statement: a query on the same connection is rejected
 *       while an insert stream is open, and works again after finish.
 *   10. cancel is idempotent; cancel-then-destroy releases the stream and
 *       the connection stays usable for queries and a fresh stream.
 *   11. Init errors (bad target table) surface via chdb_stream_insert_error
 *       on a non-NULL handle.
 *   12. destroy without done/cancel implicitly cancels: nothing committed,
 *       the single-active-statement slot is released.
 *   13. NULL-argument hardening across the whole ABI surface.
 *   14. INSERT INTO FUNCTION file(...) target: stream, finish, read back.
 *   15. Parquet input (non-streamable format): chunks buffered until done,
 *       exact values — payload generated by chdb itself via FORMAT Parquet.
 *
 * Build (against an already-built libchdb.so):
 *   clang examples/chdbStreamInsertTest.c -I./programs/local \
 *         -L. -lchdb -o examples/chdbStreamInsertTest
 *   LD_LIBRARY_PATH=. ./examples/chdbStreamInsertTest
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>

#include "chdb.h"

static int g_failed_assertions = 0;

#define CHECK(cond, msg)                                                   \
    do {                                                                   \
        if (!(cond)) {                                                     \
            fprintf(stderr, "  ASSERT FAIL: %s (%s:%d)\n",                 \
                    (msg), __FILE__, __LINE__);                            \
            g_failed_assertions += 1;                                      \
        }                                                                  \
    } while (0)

/* Runs a query, asserts it succeeded, and returns the result handle. */
static chdb_result * run(chdb_connection conn, const char * query)
{
    chdb_result * result = chdb_query(conn, query, "CSV");
    CHECK(result != NULL, query);
    if (result) {
        const char * error = chdb_result_error(result);
        if (error) {
            fprintf(stderr, "  query error: %s\n  query: %s\n", error, query);
            g_failed_assertions += 1;
        }
    }
    return result;
}

/* Runs a query and asserts its CSV output equals `expected`. */
static void expect_query(chdb_connection conn, const char * query, const char * expected)
{
    chdb_result * result = run(conn, query);
    if (!result)
        return;
    char * buf = chdb_result_buffer(result);
    size_t len = chdb_result_length(result);
    int matches = buf && len == strlen(expected) && memcmp(buf, expected, len) == 0;
    if (!matches) {
        fprintf(stderr, "  MISMATCH for %s\n    expected: %s    got: %.*s\n",
                query, expected, (int)(len > 256 ? 256 : len), buf ? buf : "(null)");
        g_failed_assertions += 1;
    }
    chdb_destroy_query_result(result);
}

/* Runs a query returning a single integer value. Returns -1 on failure. */
static long long query_int(chdb_connection conn, const char * query)
{
    chdb_result * result = run(conn, query);
    if (!result)
        return -1;
    char * buf = chdb_result_buffer(result);
    long long value = buf ? atoll(buf) : -1;
    chdb_destroy_query_result(result);
    return value;
}

/* Streams `rows` one-row CSV appends of the numbers 0..rows-1. Returns 0 on
 * the first append failure (after recording it). */
static int append_numbers_csv(chdb_insert_stream stream, uint64_t rows)
{
    char row[32];
    for (uint64_t i = 0; i < rows; i++) {
        int len = snprintf(row, sizeof(row), "%" PRIu64 "\n", i);
        if (chdb_stream_append(stream, row, (size_t)len) != CHDBSuccess) {
            const char * err = chdb_stream_insert_error(stream);
            fprintf(stderr, "  append failed at row %" PRIu64 ": %s\n",
                    i, err ? err : "(no message)");
            g_failed_assertions += 1;
            return 0;
        }
    }
    return 1;
}

static void test_full_lifecycle(chdb_connection conn)
{
    printf("== test_full_lifecycle ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st1 (a UInt64, b String) ENGINE = Memory"));

    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st1 (a, b)", "CSV");
    CHECK(stream != NULL, "stream handle is non-NULL");
    CHECK(chdb_stream_insert_error(stream) == NULL, "no init error");

    CHECK(chdb_stream_append(stream, "1,one\n", 6) == CHDBSuccess, "append #1");
    CHECK(chdb_stream_append(stream, "2,two\n", 6) == CHDBSuccess, "append #2");

    chdb_result * result = chdb_stream_done(stream);
    CHECK(result != NULL, "done returns a result");
    if (result) {
        CHECK(chdb_result_error(result) == NULL, "done reports no error");
        CHECK(chdb_result_rows_written(result) == 2, "rows_written == 2");
        CHECK(chdb_result_bytes_written(result) > 0, "bytes_written > 0");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream);

    expect_query(conn, "SELECT a, b FROM st1 ORDER BY a", "1,\"one\"\n2,\"two\"\n");
}

/* One helper for the per-format tests: stream two rows in `format`, finish,
 * and verify the exact table contents. */
static void format_roundtrip(chdb_connection conn, const char * table,
                             const char * format, const char * payload)
{
    char query[128];
    snprintf(query, sizeof(query), "CREATE TABLE %s (a UInt64, b String) ENGINE = Memory", table);
    chdb_destroy_query_result(run(conn, query));

    snprintf(query, sizeof(query), "INSERT INTO %s (a, b)", table);
    chdb_insert_stream stream = chdb_stream_insert(conn, query, format);
    CHECK(stream != NULL, "stream handle is non-NULL");
    const char * init_err = chdb_stream_insert_error(stream);
    if (init_err) {
        fprintf(stderr, "  init error for format %s: %s\n", format, init_err);
        g_failed_assertions += 1;
        chdb_destroy_insert_stream(stream);
        return;
    }

    CHECK(chdb_stream_append(stream, payload, strlen(payload)) == CHDBSuccess, format);

    chdb_result * result = chdb_stream_done(stream);
    if (result) {
        const char * err = chdb_result_error(result);
        if (err) {
            fprintf(stderr, "  done error for format %s: %s\n", format, err);
            g_failed_assertions += 1;
        }
        CHECK(chdb_result_rows_written(result) == 2, "rows_written == 2");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream);

    snprintf(query, sizeof(query), "SELECT a, b FROM %s ORDER BY a", table);
    expect_query(conn, query, "1,\"one\"\n2,\"two\"\n");
}

static void test_format_matrix(chdb_connection conn)
{
    printf("== test_format_matrix (TSV / JSONEachRow / Values) ==\n");
    format_roundtrip(conn, "stf_tsv", "TSV", "1\tone\n2\ttwo\n");
    /* JSONEachRow is the regression format for the parallel-parsing init
     * hang: with input_format_parallel_parsing left on, init never returns. */
    format_roundtrip(conn, "stf_json", "JSONEachRow",
                     "{\"a\":1,\"b\":\"one\"}\n{\"a\":2,\"b\":\"two\"}\n");
    format_roundtrip(conn, "stf_values", "Values", "(1,'one'),(2,'two')");
}

static void test_multi_chunk_streaming(chdb_connection conn)
{
    printf("== test_multi_chunk_streaming ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st2 (a UInt64) ENGINE = MergeTree ORDER BY a"));

    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st2 (a)", "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");

    /* One row per append: the shape of a record-by-record producer. */
    const uint64_t n = 20000;
    append_numbers_csv(stream, n);

    chdb_result * result = chdb_stream_done(stream);
    CHECK(result != NULL, "done returns a result");
    if (result) {
        CHECK(chdb_result_error(result) == NULL, "done reports no error");
        CHECK(chdb_result_rows_written(result) == n, "rows_written == n");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream);

    /* sum(0..n-1) = n*(n-1)/2 */
    expect_query(conn, "SELECT count(), sum(a) FROM st2", "20000,199990000\n");
}

static void test_multi_block_streaming_parts(chdb_connection conn)
{
    printf("== test_multi_block_streaming_parts ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE stp (a UInt64) ENGINE = MergeTree ORDER BY a"));

    /* Small insert blocks force the worker to push multiple blocks through
     * sendData as appends arrive; each block lands as a separate part. With
     * default (~1M-row) blocks this data would coalesce into one part. */
    chdb_insert_stream stream = chdb_stream_insert(
        conn,
        "INSERT INTO stp (a) SETTINGS max_insert_block_size=10000, "
        "min_insert_block_size_rows=10000, min_insert_block_size_bytes=0",
        "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");

    const uint64_t n = 50000;
    append_numbers_csv(stream, n);

    chdb_result * result = chdb_stream_done(stream);
    if (result) {
        CHECK(chdb_result_error(result) == NULL, "done reports no error");
        CHECK(chdb_result_rows_written(result) == n, "rows_written == n");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream);

    long long parts = query_int(conn,
        "SELECT count() FROM system.parts WHERE table='stp' AND active");
    CHECK(parts >= 2, "expected >= 2 parts => multiple streamed blocks");
    expect_query(conn, "SELECT count(), sum(a) FROM stp", "50000,1249975000\n");
}

static void test_binary_safe_length(chdb_connection conn)
{
    printf("== test_binary_safe_length ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st3 (a UInt64) ENGINE = Memory"));

    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st3 (a)", "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");

    /* Only the first 6 bytes are valid; the rest must be ignored. */
    const char buf[] = "1\n2\n3\n\0GARBAGE_BEYOND_LEN";
    CHECK(chdb_stream_append(stream, buf, 6) == CHDBSuccess, "length-bounded append");

    chdb_result * result = chdb_stream_done(stream);
    if (result) {
        CHECK(chdb_result_error(result) == NULL, "done reports no error");
        CHECK(chdb_result_rows_written(result) == 3, "rows_written == 3");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream);

    expect_query(conn, "SELECT sum(a) FROM st3", "6\n");
}

static void test_empty_stream(chdb_connection conn)
{
    printf("== test_empty_stream ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st5 (a UInt64) ENGINE = Memory"));

    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st5 (a)", "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");

    chdb_result * result = chdb_stream_done(stream);
    if (result) {
        CHECK(chdb_result_error(result) == NULL, "done on empty stream is ok");
        CHECK(chdb_result_rows_written(result) == 0, "rows_written == 0");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream);

    expect_query(conn, "SELECT count() FROM st5", "0\n");
}

static void test_post_done_contract(chdb_connection conn)
{
    printf("== test_post_done_contract ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st6 (a UInt64) ENGINE = Memory"));

    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st6 (a)", "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");
    CHECK(chdb_stream_append(stream, "1\n", 2) == CHDBSuccess, "append before done");

    chdb_result * result = chdb_stream_done(stream);
    if (result) {
        CHECK(chdb_result_error(result) == NULL, "first done ok");
        chdb_destroy_query_result(result);
    }

    /* Appending to a finalized stream must fail cleanly. */
    CHECK(chdb_stream_append(stream, "2\n", 2) == CHDBError, "append after done fails");

    /* A second done must report an error, not commit or crash. */
    chdb_result * result2 = chdb_stream_done(stream);
    CHECK(result2 != NULL, "second done returns a result");
    if (result2) {
        CHECK(chdb_result_error(result2) != NULL, "second done reports an error");
        chdb_destroy_query_result(result2);
    }
    chdb_destroy_insert_stream(stream);

    expect_query(conn, "SELECT count() FROM st6", "1\n");
}

static void test_malformed_row_error(chdb_connection conn)
{
    printf("== test_malformed_row_error ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st7 (a UInt64) ENGINE = Memory"));

    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st7 (a)", "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");

    /* Parsing happens asynchronously on the worker: the failure may surface
     * on this append or at done(), but no later — and nothing is committed. */
    chdb_state append_state = chdb_stream_append(stream, "abc\n", 4);

    chdb_result * result = chdb_stream_done(stream);
    CHECK(result != NULL, "done returns a result");
    int error_surfaced = (append_state == CHDBError);
    if (result) {
        if (chdb_result_error(result) != NULL)
            error_surfaced = 1;
        chdb_destroy_query_result(result);
    }
    CHECK(error_surfaced, "malformed row error surfaced by done() at latest");
    chdb_destroy_insert_stream(stream);

    expect_query(conn, "SELECT count() FROM st7", "0\n");
}

static void test_concurrent_statement_rejected(chdb_connection conn)
{
    printf("== test_concurrent_statement_rejected ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st8 (a UInt64) ENGINE = Memory"));

    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st8 (a)", "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");
    CHECK(chdb_stream_append(stream, "1\n", 2) == CHDBSuccess, "append");

    /* Single-active-statement: a query while the stream is open must be
     * rejected with an error result, not run. */
    chdb_result * blocked = chdb_query(conn, "SELECT 1", "CSV");
    CHECK(blocked != NULL, "query returns a result");
    if (blocked) {
        CHECK(chdb_result_error(blocked) != NULL, "query while insert active is rejected");
        chdb_destroy_query_result(blocked);
    }

    /* A second insert stream must be rejected too. */
    chdb_insert_stream stream2 = chdb_stream_insert(conn, "INSERT INTO st8 (a)", "CSV");
    CHECK(stream2 != NULL, "second stream handle non-NULL");
    if (stream2) {
        CHECK(chdb_stream_insert_error(stream2) != NULL, "second concurrent stream is rejected");
        chdb_destroy_insert_stream(stream2);
    }

    chdb_result * result = chdb_stream_done(stream);
    if (result) {
        CHECK(chdb_result_error(result) == NULL, "done ok after rejected attempts");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream);

    /* Connection works again after finish. */
    expect_query(conn, "SELECT count() FROM st8", "1\n");
}

static void test_init_error_surfaces(chdb_connection conn)
{
    printf("== test_init_error_surfaces ==\n");
    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO no_such_table (a)", "CSV");
    CHECK(stream != NULL, "handle is non-NULL even on init failure");
    if (stream) {
        const char * err = chdb_stream_insert_error(stream);
        CHECK(err != NULL, "init error message is set");
        chdb_destroy_insert_stream(stream);
    }
}

static void test_cancel_then_destroy(chdb_connection conn)
{
    printf("== test_cancel_then_destroy ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st4 (a UInt64) ENGINE = Memory"));

    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st4 (a)", "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");
    CHECK(chdb_stream_append(stream, "1\n", 2) == CHDBSuccess, "append before cancel");

    chdb_stream_cancel_insert(stream);
    /* cancel is idempotent: a second cancel must be a harmless no-op. */
    chdb_stream_cancel_insert(stream);
    chdb_destroy_insert_stream(stream);

    /* Unfinalized single-block insert commits nothing, and the connection
     * must remain usable for both queries and a fresh insert stream. */
    expect_query(conn, "SELECT count() FROM st4", "0\n");

    chdb_insert_stream stream2 = chdb_stream_insert(conn, "INSERT INTO st4 (a)", "CSV");
    CHECK(stream2 != NULL && chdb_stream_insert_error(stream2) == NULL, "new stream after cancel");
    CHECK(chdb_stream_append(stream2, "7\n", 2) == CHDBSuccess, "append on new stream");
    chdb_result * result = chdb_stream_done(stream2);
    if (result) {
        CHECK(chdb_result_rows_written(result) == 1, "rows_written == 1 after re-insert");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream2);

    expect_query(conn, "SELECT a FROM st4", "7\n");
}

static void test_destroy_without_finalize(chdb_connection conn)
{
    printf("== test_destroy_without_finalize ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st10 (a UInt64) ENGINE = Memory"));

    /* Destroying a live stream with neither done() nor cancel() must
     * internally cancel it (the C analog of Python's `with` block exiting
     * without finish()): nothing is committed, nothing leaks, and the
     * connection stays usable. */
    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st10 (a)", "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");
    CHECK(chdb_stream_append(stream, "1\n2\n", 4) == CHDBSuccess, "append");
    chdb_destroy_insert_stream(stream);

    expect_query(conn, "SELECT count() FROM st10", "0\n");

    /* The single-active-statement slot must have been released. */
    chdb_insert_stream stream2 = chdb_stream_insert(conn, "INSERT INTO st10 (a)", "CSV");
    CHECK(stream2 != NULL && chdb_stream_insert_error(stream2) == NULL,
          "new stream after destroy-without-finalize");
    CHECK(chdb_stream_append(stream2, "5\n", 2) == CHDBSuccess, "append on new stream");
    chdb_result * result = chdb_stream_done(stream2);
    if (result) {
        CHECK(chdb_result_rows_written(result) == 1, "rows_written == 1");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream2);
    expect_query(conn, "SELECT a FROM st10", "5\n");
}

static void test_null_argument_hardening(void)
{
    printf("== test_null_argument_hardening ==\n");

    CHECK(chdb_stream_append(NULL, "1\n", 2) == CHDBError, "append(NULL) fails");
    CHECK(chdb_stream_insert_error(NULL) == NULL, "error(NULL) is NULL");
    chdb_stream_cancel_insert(NULL);   /* must be a no-op, not a crash */
    chdb_destroy_insert_stream(NULL);  /* must be a no-op, not a crash */

    chdb_result * result = chdb_stream_done(NULL);
    CHECK(result != NULL, "done(NULL) returns an error result");
    if (result) {
        CHECK(chdb_result_error(result) != NULL, "done(NULL) reports an error");
        chdb_destroy_query_result(result);
    }

    /* NULL connection: handle is non-NULL and carries the error. */
    chdb_insert_stream stream = chdb_stream_insert(NULL, "INSERT INTO t (a)", "CSV");
    CHECK(stream != NULL, "insert(NULL conn) returns a handle");
    if (stream) {
        CHECK(chdb_stream_insert_error(stream) != NULL, "insert(NULL conn) carries an error");
        chdb_destroy_insert_stream(stream);
    }
}

static void test_file_target_roundtrip(chdb_connection conn)
{
    printf("== test_file_target_roundtrip ==\n");
    const char * path = "chdb_stream_c_out.csv";
    remove(path);

    chdb_insert_stream stream = chdb_stream_insert(
        conn,
        "INSERT INTO FUNCTION file('chdb_stream_c_out.csv', 'CSV', 'a UInt64, b String')",
        "CSV");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");

    CHECK(chdb_stream_append(stream, "1,one\n", 6) == CHDBSuccess, "append #1");
    CHECK(chdb_stream_append(stream, "2,two\n", 6) == CHDBSuccess, "append #2");

    chdb_result * result = chdb_stream_done(stream);
    if (result) {
        CHECK(chdb_result_error(result) == NULL, "done reports no error");
        CHECK(chdb_result_rows_written(result) == 2, "rows_written == 2");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream);

    expect_query(conn,
        "SELECT a, b FROM file('chdb_stream_c_out.csv', 'CSV', 'a UInt64, b String') ORDER BY a",
        "1,\"one\"\n2,\"two\"\n");
    remove(path);
}

static void test_parquet_buffered_input(chdb_connection conn)
{
    printf("== test_parquet_buffered_input ==\n");
    chdb_destroy_query_result(run(conn, "CREATE TABLE st9 (a UInt64, b String) ENGINE = Memory"));

    /* Generate a complete Parquet payload with chdb itself. */
    chdb_result * parquet = chdb_query(
        conn, "SELECT number AS a, toString(number) AS b FROM numbers(100)", "Parquet");
    CHECK(parquet != NULL && chdb_result_error(parquet) == NULL, "parquet generation ok");
    if (!parquet || chdb_result_error(parquet)) {
        if (parquet)
            chdb_destroy_query_result(parquet);
        return;
    }
    char * payload = chdb_result_buffer(parquet);
    size_t payload_len = chdb_result_length(parquet);
    CHECK(payload != NULL && payload_len > 0, "parquet payload non-empty");

    chdb_insert_stream stream = chdb_stream_insert(conn, "INSERT INTO st9 (a, b)", "Parquet");
    CHECK(stream != NULL && chdb_stream_insert_error(stream) == NULL, "init ok");

    /* Parquet has a trailing footer => not streamable; the chunks must be
     * buffered and parsed only at done(). Split the file to exercise that,
     * and note the payload contains NUL bytes (binary safety again). */
    size_t half = payload_len / 2;
    CHECK(chdb_stream_append(stream, payload, half) == CHDBSuccess, "append first half");
    CHECK(chdb_stream_append(stream, payload + half, payload_len - half) == CHDBSuccess,
          "append second half");
    chdb_destroy_query_result(parquet);

    chdb_result * result = chdb_stream_done(stream);
    if (result) {
        const char * err = chdb_result_error(result);
        if (err) {
            fprintf(stderr, "  parquet done error: %s\n", err);
            g_failed_assertions += 1;
        }
        CHECK(chdb_result_rows_written(result) == 100, "rows_written == 100");
        chdb_destroy_query_result(result);
    }
    chdb_destroy_insert_stream(stream);

    /* sum(0..99) = 4950; spot-check a value to prove column integrity. */
    expect_query(conn, "SELECT count(), sum(a) FROM st9", "100,4950\n");
    expect_query(conn, "SELECT b FROM st9 WHERE a = 42", "\"42\"\n");
}

int main(int argc, char ** argv)
{
    (void)argc; (void)argv;

    char arg0[] = "clickhouse";
    char arg1[] = "--multiquery";
    char * args[] = {arg0, arg1};
    chdb_connection * conn = chdb_connect(2, args);
    if (!conn) {
        fprintf(stderr, "chdb_connect failed\n");
        return 1;
    }

    test_full_lifecycle(*conn);
    test_format_matrix(*conn);
    test_multi_chunk_streaming(*conn);
    test_multi_block_streaming_parts(*conn);
    test_binary_safe_length(*conn);
    test_empty_stream(*conn);
    test_post_done_contract(*conn);
    test_malformed_row_error(*conn);
    test_concurrent_statement_rejected(*conn);
    test_init_error_surfaces(*conn);
    test_cancel_then_destroy(*conn);
    test_destroy_without_finalize(*conn);
    test_null_argument_hardening();
    test_file_target_roundtrip(*conn);
    test_parquet_buffered_input(*conn);

    chdb_close_conn(conn);

    printf("\n== summary: %d failed assertions ==\n", g_failed_assertions);
    return g_failed_assertions == 0 ? 0 : 1;
}
